 raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stat.ripe.net', port=443): Max retries exceeded with url: /data/country-asns/data.json?resource=jo&lod=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff749ee6b70>: Failed to establish a new connection: [Errno -2] Name or service not known',))

